<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HMECD000787" name="com.truaxis.test.reporting.Scenario3Test" tests="7" failures="0" timestamp="2 Dec 2013 04:38:56 GMT" time="0.688" errors="1">
  <testcase name="testRD_3_1" time="0.031" classname="com.truaxis.test.reporting.Scenario3Test"/>
  <testcase name="testRD_3_3" time="0.078" classname="com.truaxis.test.reporting.Scenario3Test"/>
  <testcase name="testRD_3_6" time="0.031" classname="com.truaxis.test.reporting.Scenario3Test"/>
  <testcase name="testRD_3_7" time="0.297" classname="com.truaxis.test.reporting.Scenario3Test"/>
  <testcase name="testRD_3_2" time="0.095" classname="com.truaxis.test.reporting.Scenario3Test">
    <error type="java.lang.AssertionError" message="Export,PDF,Exel,CSV labels,are not displayed on Statement Credit page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Export,PDF,Exel,CSV labels,are not displayed on Statement Credit page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.truaxis.test.reporting.Scenario3Test.testRD_3_2(Scenario3Test.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testRD_3_2 -->
  <testcase name="testRD_3_4" time="0.078" classname="com.truaxis.test.reporting.Scenario3Test"/>
  <testcase name="testRD_3_5" time="0.078" classname="com.truaxis.test.reporting.Scenario3Test"/>
</testsuite> <!-- com.truaxis.test.reporting.Scenario3Test -->
